from collections.abc import Iterator

class Document:
    """A parsed XML document backed by a SIMD-accelerated structural index."""

    @property
    def root(self) -> Element | None: ...
    @property
    def tag_count(self) -> int: ...
    def xpath_text(self, expr: str) -> list[str]: ...
    def xpath_string(self, expr: str) -> list[str]: ...
    def xpath(self, expr: str) -> list[Element | str]: ...

class Element:
    """A read-only element in a parsed XML document."""

    @property
    def tag(self) -> str: ...
    @property
    def text(self) -> str | None: ...
    @property
    def tail(self) -> str | None: ...
    @property
    def attrib(self) -> dict[str, str]: ...
    def get(self, key: str, default: str | None = None) -> str | None: ...
    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def iter(self, tag: str | None = None) -> Iterator[Element]: ...
    def itertext(self) -> list[str]: ...
    def text_content(self) -> str: ...
    def xpath(self, expr: str) -> list[Element]: ...
    def xpath_text(self, expr: str) -> list[str]: ...
    def getparent(self) -> Element | None: ...
    def getnext(self) -> Element | None: ...
    def getprevious(self) -> Element | None: ...
    def tostring(self) -> str: ...
    # Read-only enforcement: these raise TypeError
    def set(self, key: str, value: str) -> None: ...
    def append(self, element: Element) -> None: ...
    def remove(self, element: Element) -> None: ...
    def insert(self, index: int, element: Element) -> None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Element: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class CompiledXPath:
    """A compiled XPath expression for repeated evaluation."""

    def eval_text(self, doc: Document) -> list[str]: ...
    def eval(self, doc: Document) -> list[Element]: ...
    def eval_exists(self, doc: Document) -> bool: ...
    def eval_count(self, doc: Document) -> int: ...

def parse(data: bytes | str) -> Document: ...
def compile(expr: str) -> CompiledXPath: ...
